import type { StoryDefinition, StoryStep } from './story.types'

const steps: StoryStep[] = [
  {
    id: 'chapter-title',
    kind: 'title',
    screen: 'black',
    text: 'Chapter One: Arrival at the Fief',
    next: 'intro-bells',
  },
  {
    id: 'intro-bells',
    kind: 'narration',
    screen: 'black',
    text: 'On a rainy night, the bells of the royal capital struck twelve.',
    next: 'intro-crest',
  },
  {
    id: 'intro-crest',
    kind: 'narration',
    screen: 'black',
    text: 'Your family crest was taken down from the council hall wall. The old nobles watched coldly, while trade guild delegates laughed under their breath.',
    next: 'intro-mist',
  },
  {
    id: 'intro-mist',
    kind: 'narration',
    screen: 'black',
    text: '"New Haven? A fief swallowed by sea fog dares call itself a domain?"',
    next: 'intro-contract',
  },
  {
    id: 'intro-contract',
    kind: 'narration',
    screen: 'black',
    text: "You stood outside the door, clutching the sailing contract your father left behind.",
    next: 'intro-assets',
  },
  {
    id: 'intro-assets',
    kind: 'narration',
    screen: 'black',
    text: "It was a yellowed piece of parchment listing your family's last assets: an abandoned harbor, a stretch of barren land, and a few trade routes nearly cut off from the world.",
    next: 'intro-exile',
  },
  {
    id: 'intro-exile',
    kind: 'narration',
    screen: 'black',
    text: 'Everyone believed this was exile.',
    next: 'intro-last-words',
  },
  {
    id: 'intro-last-words',
    kind: 'narration',
    screen: 'black',
    text: 'But before he died, your father left only one sentence: "Do not look back. Go to New Haven. That is where our family truly begins."',
    next: 'intro-boat',
  },
  {
    id: 'intro-boat',
    kind: 'narration',
    screen: 'black',
    text: 'Before dawn, you boarded a worn little boat.',
    next: 'intro-owner',
  },
  {
    id: 'intro-owner',
    kind: 'narration',
    screen: 'black',
    text: 'The lights of the royal capital faded behind you. At the edge of the horizon, a forgotten harbor waited for its new master.',
    next: 'arrival-boat',
  },
  {
    id: 'arrival-boat',
    kind: 'narration',
    screen: 'harbor',
    boat: 'arriving',
    text: 'The worn little boat slowly drew alongside the dock.',
    next: 'arrival-cloak',
  },
  {
    id: 'arrival-cloak',
    kind: 'narration',
    screen: 'harbor',
    boat: 'docked',
    text: 'The sea breeze lifted your faded noble cloak. This was the fief you had inherited.',
    next: 'arrival-name',
  },
  {
    id: 'arrival-name',
    kind: 'title',
    screen: 'harbor',
    boat: 'docked',
    locationTitle: 'New Haven',
    text: 'New Haven',
    next: 'cecil-shadow',
  },
  {
    id: 'cecil-shadow',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: '???',
    portrait: 'shadow',
    boat: 'docked',
    text: 'Young Lord, welcome back to your fief. Though it holds only barren fields, an old warehouse, and a few trade roads no one dares travel... it still belongs to your family.',
    next: 'cecil-reveal',
  },
  {
    id: 'cecil-reveal',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'The late lord entrusted me to support you, and to serve as your guardian. My name is Cecil Ashwing. Welcome to New Haven.',
    next: 'choice-doubt',
  },
  {
    id: 'choice-doubt',
    kind: 'choice',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'How will you answer?',
    choices: [
      { label: 'No one believes in this place?', next: 'doubt-a' },
      { label: 'Mother.', next: 'doubt-b-silence' },
    ],
  },
  {
    id: 'doubt-a',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'Yes. The people in the capital all say this fief has no value left.',
    next: 'young-perfect',
  },
  {
    id: 'doubt-b-silence',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: '...',
    next: 'doubt-b-complex',
  },
  {
    id: 'doubt-b-complex',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'Young Lord, please do not make our guardianship so complicated on the first day of our family revival.',
    next: 'doubt-b-vow',
  },
  {
    id: 'doubt-b-vow',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'However... if that is your command, I shall guard you in the name of Ashwing until the stars fall into the sea and the royal banner returns.',
    next: 'young-perfect',
  },
  {
    id: 'young-perfect',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Young Lord',
    portrait: 'cecil',
    boat: 'docked',
    text: 'Perfect.',
    next: 'narrator-smile',
  },
  {
    id: 'narrator-smile',
    kind: 'narration',
    screen: 'harbor',
    portrait: 'cecil',
    boat: 'docked',
    text: 'You smiled softly and looked toward the silent harbor in the distance.',
    next: 'young-ambition',
  },
  {
    id: 'young-ambition',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Young Lord',
    portrait: 'cecil',
    boat: 'docked',
    text: 'If no one is fighting for it, then this is exactly where I can make my mark.',
    next: 'choice-cecil',
  },
  {
    id: 'choice-cecil',
    kind: 'choice',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'What will you call her?',
    choices: [
      { label: "Then I'll be counting on you, Lady Cecil.", next: 'cecil-a' },
      { label: "Then I'll be counting on you, Little Ash.", next: 'cecil-b-name' },
    ],
  },
  {
    id: 'cecil-a',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'As you command, Young Lord. From this day forth, I will assist you in rebuilding the fief.',
    next: 'young-richest',
  },
  {
    id: 'cecil-b-name',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: '...We can discuss forms of address another time.',
    next: 'cecil-b-record',
  },
  {
    id: 'cecil-b-record',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Cecil Ashwing',
    portrait: 'cecil',
    boat: 'docked',
    text: 'But if this is the command of New Haven\'s future ruler, I will remember it.',
    next: 'young-richest',
  },
  {
    id: 'young-richest',
    kind: 'dialogue',
    screen: 'harbor',
    speaker: 'Young Lord',
    portrait: 'cecil',
    boat: 'docked',
    text: 'Starting today, this place will become the richest land in the kingdom once again.',
    next: 'system-objective',
  },
  {
    id: 'system-objective',
    kind: 'system',
    screen: 'harbor',
    speaker: 'System',
    portrait: 'cecil',
    boat: 'docked',
    text: 'New Tutorial Objective Unlocked: Repair the old dock and rebuild your first warehouse.',
    actionLabel: 'Begin Building',
  },
]

export const chapter1ArrivalStory: StoryDefinition = {
  id: 'chapter1Arrival',
  title: 'Chapter One: Arrival at the Fief',
  firstStepId: 'chapter-title',
  steps,
}
